# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in passman.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "standard", "~> 1.3"

gem "pry"

gem "highline"

gem 'zxcvbn-ruby', require: 'zxcvbn'

gem 'tty-prompt'

gem 'tty-logger'

gem 'tty-screen' 

gem 'tty-table'    

gem 'tty-box'  

gem 'tty-cursor'  

gem 'tty-command'  

gem 'tty-reader'    